# 20736A1 firmware build 112
# patch entries used: 45 out of 64 elf patches, 70%
CY_PATCH_ENTRIES_BASE=45
# additional patch entries in these libraries:
#   1 in pmu_fixes.a
#   1 in ll_terminate_to.a
#   4 in rtc_api.a
#   1 in single_channel_scan.a
#   1 in always_enable_transport_sleep.a
#   4 in bleapp_lib.a
#   1 in blecen_read_dbg_uart_on_timeout.a
#   3 in config_nvram_fixes.a
#   1 in application_poll_notification.a
#   1 in hci_uart_pins_as_gpio.a
#   2 in central_role_patches.a
#   2 in additional_advertisement_control.a
#   1 in smp_multi_key_storage.a
#   3 in long_characteristic_support.a
#   1 in disable_sw_timer_as_wake_source.a
#   1 in hw_timer.a
#   1 in additional_gatt_apis.a
#   1 in mia_hidoff_fixes.a
#   1 in mic_error_bypass.a
#   2 in sfi_ultra_deep.a
#   1 in wdog_lib.a
# patch ram used: 10040 out of 20480 bytes, 49%
